name: React CI/CD to VPS - BUILD ONLY

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    - name: Install dependencies
      run: npm install
    - name: Build
      env:
      VITE_COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
      run: npm run build
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: dist/
